# Generated by Django 3.2.1 on 2021-07-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_auto_20210728_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='signup_user',
            name='gender',
        ),
    ]
