# Generated by Django 3.2.1 on 2021-07-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_auto_20210728_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signup_user',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='signup_user',
            name='password',
        ),
    ]
