# Generated by Django 3.2.1 on 2021-07-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0005_auto_20210729_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='testing',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
