# Generated by Django 3.2.1 on 2021-07-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0007_auto_20210729_0027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup_user',
            new_name='signup',
        ),
    ]
