# Generated by Django 3.2.1 on 2021-07-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0008_rename_signup_user_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='gender',
        ),
    ]
