# Generated by Django 3.2.1 on 2021-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0010_alter_signup_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='mobile_number',
            new_name='mobilenumber',
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
