# Generated by Django 3.2.1 on 2021-07-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0011_auto_20210729_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='birthday',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
