# Generated by Django 3.2.1 on 2021-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0012_auto_20210729_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='birthday',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobilenumber',
            field=models.IntegerField(max_length=30),
        ),
    ]
