# Generated by Django 3.2.1 on 2021-07-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0014_auto_20210729_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='passworrd',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='gender',
        ),
    ]
