# Generated by Django 3.2.1 on 2021-07-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0015_auto_20210729_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
