# Generated by Django 3.2.1 on 2021-07-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0021_alter_signupp_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupp',
        ),
    ]
