# Generated by Django 3.2.1 on 2021-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fb', '0022_delete_signupp'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mobilenumber', models.IntegerField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
