# Generated by Django 3.2.1 on 2021-07-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0023_signupp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signupp',
            name='password',
        ),
        migrations.AlterField(
            model_name='signupp',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb.signupp')),
            ],
        ),
    ]
