# Generated by Django 3.2.1 on 2021-07-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0026_alter_signupp_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupp',
            name='birthday',
            field=models.DateField(),
        ),
    ]
