# Generated by Django 3.2.1 on 2021-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0027_alter_signupp_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupp',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signupp',
            name='firstname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='signupp',
            name='lastname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='signupp',
            name='mobilenumber',
            field=models.IntegerField(max_length=60),
        ),
    ]
