# Generated by Django 3.2.1 on 2021-07-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0028_auto_20210730_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='signupp',
        ),
    ]
