# Generated by Django 3.2.1 on 2021-07-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0030_login_signupp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupp',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
