# Generated by Django 3.2.1 on 2021-07-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0035_alter_signupp_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupp',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
